<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Aluno;

class AlunoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $alunos = [
            [
                'matricula' => '2024001',
                'nome' => 'Ana Silva Santos',
                'email' => 'ana.santos@estudante.ivoti.edu.br',
                'telefone' => '(51) 99999-1111',
                'data_nascimento' => '2007-03-15',
                'endereco' => 'Rua das Flores, 123 - Centro',
                'turma' => '3º A',
                'curso' => 'Formação Básica',
                'responsavel' => 'Maria Santos',
                'telefone_responsavel' => '(51) 99999-1112',
                'status' => 'Ativo',
                'observacoes' => 'Aluna dedicada, participa ativamente das aulas.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'matricula' => '2024002',
                'nome' => 'Bruno Costa Lima',
                'email' => 'bruno.lima@estudante.ivoti.edu.br',
                'telefone' => '(51) 99999-2222',
                'data_nascimento' => '2006-08-22',
                'endereco' => 'Av. Principal, 456 - Bairro Novo',
                'turma' => '3º A',
                'curso' => 'Itinerário de Exatas',
                'responsavel' => 'João Lima',
                'telefone_responsavel' => '(51) 99999-2223',
                'status' => 'Ativo',
                'observacoes' => 'Excelente em matemática e física.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'matricula' => '2024003',
                'nome' => 'Carla Oliveira Pereira',
                'email' => 'carla.pereira@estudante.ivoti.edu.br',
                'telefone' => '(51) 99999-3333',
                'data_nascimento' => '2007-01-10',
                'endereco' => 'Rua da Paz, 789 - Jardim',
                'turma' => '2º B',
                'curso' => 'Itinerário de Humanas',
                'responsavel' => 'Pedro Pereira',
                'telefone_responsavel' => '(51) 99999-3334',
                'status' => 'Ativo',
                'observacoes' => 'Interessada em história e geografia.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'matricula' => '2024004',
                'nome' => 'Diego Rodrigues Silva',
                'email' => 'diego.silva@estudante.ivoti.edu.br',
                'telefone' => '(51) 99999-4444',
                'data_nascimento' => '2006-11-05',
                'endereco' => 'Av. Central, 321 - Centro',
                'turma' => '3º C',
                'curso' => 'Técnico em Informática',
                'responsavel' => 'Silvia Rodrigues',
                'telefone_responsavel' => '(51) 99999-4445',
                'status' => 'Ativo',
                'observacoes' => 'Apaixonado por programação e tecnologia.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'matricula' => '2024005',
                'nome' => 'Elena Ferreira Costa',
                'email' => 'elena.costa@estudante.ivoti.edu.br',
                'telefone' => '(51) 99999-5555',
                'data_nascimento' => '2007-06-18',
                'endereco' => 'Rua das Palmeiras, 654 - Vila Nova',
                'turma' => '1º A',
                'curso' => 'Técnico em Design',
                'responsavel' => 'Roberto Ferreira',
                'telefone_responsavel' => '(51) 99999-5556',
                'status' => 'Ativo',
                'observacoes' => 'Muito criativa, destaque em artes.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'matricula' => '2024006',
                'nome' => 'Felipe Almeida Santos',
                'email' => 'felipe.santos@estudante.ivoti.edu.br',
                'telefone' => '(51) 99999-6666',
                'data_nascimento' => '2006-09-12',
                'endereco' => 'Rua do Sol, 987 - Bairro Alto',
                'turma' => '2º C',
                'curso' => 'Técnico em Agropecuária',
                'responsavel' => 'Lucia Almeida',
                'telefone_responsavel' => '(51) 99999-6667',
                'status' => 'Ativo',
                'observacoes' => 'Interessado em sustentabilidade e meio ambiente.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'matricula' => '2024007',
                'nome' => 'Gabriela Martins Lima',
                'email' => 'gabriela.lima@estudante.ivoti.edu.br',
                'telefone' => '(51) 99999-7777',
                'data_nascimento' => '2007-04-25',
                'endereco' => 'Av. das Flores, 147 - Centro',
                'turma' => '3º B',
                'curso' => 'Itinerário de Biológicas',
                'responsavel' => 'Carlos Martins',
                'telefone_responsavel' => '(51) 99999-7778',
                'status' => 'Ativo',
                'observacoes' => 'Futura médica, excelente em biologia.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'matricula' => '2024008',
                'nome' => 'Henrique Souza Oliveira',
                'email' => 'henrique.oliveira@estudante.ivoti.edu.br',
                'telefone' => '(51) 99999-8888',
                'data_nascimento' => '2006-12-03',
                'endereco' => 'Rua da Liberdade, 258 - Jardim',
                'turma' => '1º B',
                'curso' => 'Formação Básica',
                'responsavel' => 'Patricia Souza',
                'telefone_responsavel' => '(51) 99999-8889',
                'status' => 'Inativo',
                'observacoes' => 'Transferido para outra escola.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'matricula' => '2024009',
                'nome' => 'Isabela Rocha Pereira',
                'email' => 'isabela.pereira@estudante.ivoti.edu.br',
                'telefone' => '(51) 99999-9999',
                'data_nascimento' => '2007-07-14',
                'endereco' => 'Av. Brasil, 369 - Centro',
                'turma' => '2º A',
                'curso' => 'Itinerário de Linguagens',
                'responsavel' => 'Antonio Rocha',
                'telefone_responsavel' => '(51) 99999-0000',
                'status' => 'Ativo',
                'observacoes' => 'Destaque em literatura e redação.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'matricula' => '2024010',
                'nome' => 'João Pedro Silva Costa',
                'email' => 'joao.costa@estudante.ivoti.edu.br',
                'telefone' => '(51) 99999-1010',
                'data_nascimento' => '2006-10-30',
                'endereco' => 'Rua das Acácias, 741 - Vila Verde',
                'turma' => '3º D',
                'curso' => 'Técnico em Eletrotécnica',
                'responsavel' => 'Fernanda Silva',
                'telefone_responsavel' => '(51) 99999-1011',
                'status' => 'Ativo',
                'observacoes' => 'Interessado em engenharia elétrica.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($alunos as $aluno) {
            Aluno::create($aluno);
        }
    }
}
